#########################################################
# This file has been automatically generated by gem2tgz #
#########################################################
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "deep_merge"
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Steve Midgley"]
  s.date = "2016-08-01"
  s.description = "Recursively merge hashes."
  s.email = "dan@kallistec.com"
  s.extra_rdoc_files = ["LICENSE", "README.md"]
  s.files = ["CHANGELOG", "LICENSE", "README.md", "Rakefile", "lib/deep_merge.rb", "lib/deep_merge/core.rb", "lib/deep_merge/deep_merge_hash.rb", "lib/deep_merge/rails_compat.rb", "test/test_deep_merge.rb"]
  s.homepage = "https://github.com/danielsdeleo/deep_merge"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Merge Deeply Nested Hashes"
  s.test_files = ["test/test_deep_merge.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, ["~> 10.1"])
      s.add_development_dependency(%q<test-unit-minitest>, [">= 0"])
    else
      s.add_dependency(%q<rake>, ["~> 10.1"])
      s.add_dependency(%q<test-unit-minitest>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, ["~> 10.1"])
    s.add_dependency(%q<test-unit-minitest>, [">= 0"])
  end
end
